import{a as b,S as w,i as n}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const E="46889840-15974bab23e9bef03dd03027e",L="https://pixabay.com/api/",y=15;let p=1;async function f(o){const r=`${L}?key=${E}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${p}&per_page=${y}`;try{const e=await b.get(r);return p+=1,e.data}catch{throw new Error("Feiled to fetch images")}}function v(){p=1}function g(o){const r=document.getElementById("gallery");o.forEach(e=>{const a=document.createElement("div");a.classList.add("gallery-item"),a.innerHTML=`
            <a href="${e.largeImageURL}" class="gallery-link">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" class="img">
            </a>
            <div class="info">
                <p class="text">Likes: <span class="numbers">${e.likes}</span></p>
                <p class="text">Views: <span class="numbers">${e.views}</span></p>
                <p class="text">Comments: <span class="numbers">${e.comments}</span></p>
                <p class="text">Downloads: <span class="numbers">${e.downloads}</span></p>
            </div>
        `,r.appendChild(a)})}const h=new w(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),$=document.querySelector(".form"),l=document.getElementById("loader"),m=document.getElementById("gallery"),c=document.getElementById("load-more");let u="",i=0;$.addEventListener("submit",async function(o){o.preventDefault();const r=document.getElementById("search").value.trim();if(!r){n.error({title:"Error",message:"Search failed cannot be empty!"});return}l.style.display="block",c.style.display="none",v(),u=r,m.innerHTML="";try{const e=await f(u);i=e.totalHits,i===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ff4d4f",iconColor:"white",titleColor:"white",messageColor:"white",titleSize:"16px",position:"topRight",timeout:5e3,maxWidth:432}):(g(e.hits),h.refresh(),i>y&&(c.style.display="block"))}catch(e){n.error({title:"Error",message:e.message})}finally{l.style.display="none"}});c.addEventListener("click",async()=>{l.style.display="block";try{const o=await f(u);if(g(o.hits),h.refresh(),m.children.length>=i)c.style.display="none",n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{const{height:r}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*4,behavior:"smooth"})}}catch(o){n.error({title:"Error",message:o.message})}finally{l.style.display="none"}});
//# sourceMappingURL=index.js.map
