import{S as c,i}from"./assets/vendor-5ObWk2rO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();function d(n){const e=`https://pixabay.com/api/?key=46889840-15974bab23e9bef03dd03027e&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(e).then(o=>{if(!o.ok)throw new Error(`HTTP помилка! Статус: ${o.status}`);return o.json()})}function m(n){const s=document.getElementById("gallery");s.innerHTML="",n.forEach(e=>{const o=document.createElement("div");o.classList.add("gallery-item"),o.innerHTML=`
            <a href="${e.largeImageURL}" class="gallery-link">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" class="img">
            </a>
            <div class="info">
                <p class="text">Likes: <span class="numbers">${e.likes}</span></p>
                <p class="text">Views: <span class="numbers">${e.views}</span></p>
                <p class="text">Comments: <span class="numbers">${e.comments}</span></p>
                <p class="text">Downloads: <span class="numbers">${e.downloads}</span></p>
            </div>
        `,s.appendChild(o)})}const u=new c(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),p=document.querySelector(".form"),l=document.getElementById("loader");document.getElementById("gallery");p.addEventListener("submit",function(n){n.preventDefault();const s=document.getElementById("search").value.trim();if(!s){i.error({title:"Error",message:"Search field cannot be empty!"});return}l.style.display="flex",d(s).then(e=>{l.style.display="none",e.hits.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ff4d4f",iconColor:"white",titleColor:"white",messageColor:"white",titleSize:"16px",position:"topRight",timeout:5e3,maxWidth:432}):(m(e.hits),u.refresh())}).catch(e=>{l.style.display="none",i.error({title:"Error",message:e.message})})});
//# sourceMappingURL=index.js.map
